import AppKit
import Foundation
import Observation

/// Watches the clipboard so saving never requires deciding to save *before* you copy.
///
/// Defaults to memory-only: history is discarded when Summon quits unless you turn
/// persistence on. In an app whose promise is privacy, a clipboard log that quietly
/// survives reboots is the wrong default.
@MainActor
@Observable
public final class ClipboardMonitor {

    public struct Entry: Identifiable, Sendable, Equatable {
        public let id: UUID
        public let capturedAt: Date
        public let kind: ItemKind
        public let text: String?
        public let rtf: Data?
        public let imageData: Data?
        public let fileURL: URL?
        public let sourceBundleID: String?
        public let sourceAppName: String?

        public var preview: String {
            if let fileURL { return fileURL.lastPathComponent }
            if imageData != nil { return "Image" }
            let t = (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            return t.isEmpty ? "Empty" : String(t.prefix(200))
        }

        public var suggestedTitle: String {
            if let fileURL { return fileURL.deletingPathExtension().lastPathComponent }
            if imageData != nil {
                return "Image from \(sourceAppName ?? "clipboard")"
            }
            return Heuristics.title(forText: text ?? "")
        }
    }

    public private(set) var entries: [Entry] = []
    public var isEnabled: Bool = true { didSet { isEnabled ? start() : stop() } }
    public var persistBetweenLaunches: Bool = false
    public var maxEntries: Int = 40

    /// Apps whose copies are never recorded. Password managers are excluded by their
    /// concealed-type marker too, but explicit exclusions are belt and braces.
    public var excludedBundleIDs: Set<String> = [
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
    ]

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let paths: LibraryPaths

    /// Pasteboard markers meaning "this is a secret" or "this is transient".
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    public init(paths: LibraryPaths) {
        self.paths = paths
        loadIfPersisted()
    }

    public func start() {
        guard isEnabled, timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        // There is no change notification for NSPasteboard, so polling is the only
        // option. 0.4s is imperceptible to a person and costs essentially nothing.
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right before Summon writes to the pasteboard, so our own paste does not
    /// come back around as a new clipboard entry.
    public func ignoreNextChange() {
        lastChangeCount = NSPasteboard.general.changeCount + 1
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        // Never record something the source app marked as concealed.
        let available = pb.types ?? []
        if ClipboardMonitor.concealedTypes.contains(where: available.contains) { return }

        let front = NSWorkspace.shared.frontmostApplication
        let bundleID = front?.bundleIdentifier
        if let bundleID, excludedBundleIDs.contains(bundleID) { return }
        if bundleID == Bundle.main.bundleIdentifier { return }

        guard let entry = makeEntry(from: pb, bundleID: bundleID, appName: front?.localizedName) else { return }

        // Collapse an immediate re-copy of the same thing.
        if let first = entries.first, first.text == entry.text, first.fileURL == entry.fileURL,
           first.imageData == entry.imageData {
            return
        }

        entries.insert(entry, at: 0)
        if entries.count > maxEntries { entries.removeLast(entries.count - maxEntries) }
        persistIfNeeded()
    }

    private func makeEntry(from pb: NSPasteboard, bundleID: String?, appName: String?) -> Entry? {
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let url = urls.first, url.isFileURL {
            return Entry(id: UUID(), capturedAt: Date(), kind: ItemKind.forFile(at: url),
                         text: nil, rtf: nil, imageData: nil, fileURL: url,
                         sourceBundleID: bundleID, sourceAppName: appName)
        }
        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            return Entry(id: UUID(), capturedAt: Date(), kind: .image,
                         text: nil, rtf: nil, imageData: data, fileURL: nil,
                         sourceBundleID: bundleID, sourceAppName: appName)
        }
        if let string = pb.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            let rtf = pb.data(forType: .rtf)
            let rich = rtf.map(RTF.hasMeaningfulFormatting) ?? false
            return Entry(id: UUID(), capturedAt: Date(), kind: rich ? .richText : .text,
                         text: string, rtf: rich ? rtf : nil, imageData: nil, fileURL: nil,
                         sourceBundleID: bundleID, sourceAppName: appName)
        }
        return nil
    }

    public func clear() {
        entries.removeAll()
        try? FileManager.default.removeItem(at: historyURL)
    }

    public func remove(_ id: UUID) {
        entries.removeAll { $0.id == id }
        persistIfNeeded()
    }

    // MARK: - Optional persistence (text entries only)

    private var historyURL: URL { paths.root.appending(path: "clipboard.json") }

    private struct StoredEntry: Codable {
        var id: UUID
        var capturedAt: Date
        var text: String
        var sourceBundleID: String?
        var sourceAppName: String?
    }

    private func persistIfNeeded() {
        guard persistBetweenLaunches else { return }
        // Images and file references are never written to disk; only text is.
        let stored = entries.compactMap { e -> StoredEntry? in
            guard let text = e.text, e.imageData == nil, e.fileURL == nil else { return nil }
            return StoredEntry(id: e.id, capturedAt: e.capturedAt, text: text,
                               sourceBundleID: e.sourceBundleID, sourceAppName: e.sourceAppName)
        }
        if let data = try? JSONEncoder().encode(stored) {
            try? data.write(to: historyURL, options: [.atomic, .completeFileProtection])
        }
    }

    private func loadIfPersisted() {
        guard let data = try? Data(contentsOf: historyURL),
              let stored = try? JSONDecoder().decode([StoredEntry].self, from: data) else { return }
        entries = stored.map {
            Entry(id: $0.id, capturedAt: $0.capturedAt, kind: .text, text: $0.text,
                  rtf: nil, imageData: nil, fileURL: nil,
                  sourceBundleID: $0.sourceBundleID, sourceAppName: $0.sourceAppName)
        }
    }
}
